apiVersion: v1
kind: Service
metadata:
  name: {{ include "amplication.containerbuilder.docker.name" . }}
  labels:
    {{- include "amplication.containerbuilder.docker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.containerbuilder.docker.service.type }}
  ports:
    - name: "{{ .Values.containerbuilder.docker.name }}-tcp"
      port: {{ .Values.containerbuilder.docker.service.port }}
  selector:
    {{- include "amplication.containerbuilder.docker.selectorLabels" . | nindent 4 }}
