apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "amplication.scheduler.name" . }}
data:
  POSTGRESQL_URL: {{ .Values.scheduler.config.env.POSTGRESQL_URL | default (printf "postgres://%s:%s@%s:%v" .Values.postgres.postgresqlUsername .Values.postgres.postgresqlPassword .Values.postgres.fullnameOverride .Values.postgres.servicePort ) }}
