apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.volume.name }}
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: {{ .Values.app.volume.storageLimit }}
    requests:
      storage: {{ .Values.app.volume.storageRequest }}
