apiVersion: v1
kind: Service
metadata:
  name: {{ include "amplication.containerbuilder.registry.name" . }}
  labels:
    {{- include "amplication.containerbuilder.registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.containerbuilder.registry.service.type }}
  ports:
    - name: "{{ .Values.containerbuilder.registry.name }}-tcp"
      port: {{ .Values.containerbuilder.registry.service.port }}
  selector:
    {{- include "amplication.containerbuilder.registry.selectorLabels" . | nindent 4 }}
